# Generated by Django 3.1.2 on 2020-11-15 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GGcatalogo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventario',
            old_name='juego',
            new_name='juegos',
        ),
    ]
