# Generated by Django 3.1.2 on 2020-11-15 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GGcatalogo', '0003_auto_20201115_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desarrollador',
            name='creacion',
            field=models.DateField(blank=True, null=True, verbose_name='Creación'),
        ),
    ]
